### ISSUE TITLE
No data Visualization

### ISSUE THREAD

**Issue by Uzzi** [Zen-Networks/forti-elk#1]
Hi, I've import all files, but this is logstash log:
[2020-06-08T16:21:29,226][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2020-06-08T16:21:29,227][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}

No data in elasticsearch.

Can you helpme?

**Comment by N-faycal** [comment]
Hi there,

  Did you check using tcpdump for example if you actually receive the logs on Logstash on the correct port ?

**Comment by Uzzi** [comment]
Hi, yes of course it's first test.
input {
   udp {
     port => 514

tcpdump port 514 recive FW log

**Comment by N-faycal** [comment]
ok. Please share logstash configuration for verification. The configuration in the git should work fine. But, if there are multiple pipes, that might cause an issue

**Comment by N-faycal** [comment]
No more info provided after 2 months & issue not reproduced
